main: com.martoph.mail.MartophsMail
name: ${name}
version: ${version}
author: Martoph
description: Mail delivery system.
commands:
  endmessage:
    description: "Ends an Martoph's Mail message"
  mmail:
    description: "Starts a Martoph's Mail message"