main: com.martoph.mail.MartophsMail
name: MartophsMail
version: 1.0.3-SNAPSHOT
author: Martoph
description: Mail delivery system.
depend: [Citizens]
commands:
  endmessage:
    description: "Ends an Martoph's Mail message"
  mmail:
    description: "Starts a Martoph's Mail message"