main: com.rowlingsrealm.owlery.Owlery
name: Owlery
version: 1.0-SNAPSHOT
author: Martoph
description: Mail delivery for Rowling's Realm
depend: [Citizens]
commands:
  endmessage:
    description: "Ends an Owlery message"